version: "3.1"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=abcABC123
    volumes:
      - /var/opt/mssql:/d/Docker/mssql
    networks:
      - my-network
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
    - 5672:5672
    networks:
      - my-network
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - my-network
networks:
  my-network: